apiVersion: v1
kind: Pod
# TODO difference: Pod, Service, Deployment?
metadata:
  name: hello-k8s-pod
spec:
  containers:
    - name: users-service-container
      # as deployed to docker hub
      image: christophpickl/users-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: K8S_SERVER_PORT
          value: "80"
    - name: books-service-container
      image: christophpickl/books-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: K8S_SERVER_PORT
          value: "80"
        - name: K8S_USERS_SERVICE_BASE_URL
          value: http://localhost:8081

# Run: kubectl apply -f k8s-manifest.yaml
# Proxy: kubectl port-forward hello-k8s-pod 8082:8082